id: IA6539A9E
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:51.980771
last_modified: 2023-01-04 11:30:51.980783
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  CB4F:
    title: Prayer for the Long Life of Namkhai Norbu Rinpoche
    base_file: CB4F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
